package ec.edu.intsuperior.vista.formularios;


import ec.edu.intsuperior.controlador.Controlador;
import ec.edu.intsuperior.modelo.Consultas;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;

public class PanelAdmin extends javax.swing.JFrame {

    Controlador controlador;
     
    Consultas con = new Consultas();
    public PanelAdmin(Controlador controlador) {
        this.controlador=controlador;
        initComponents();
        this.setLocationRelativeTo(this);
        con.LeerEmpleados("empleados", jTable_empleados);
        con.LeerClientes("clientes", jTable_Clientes);
        con.LeerProductos("productos", jTable_productos);
        con.LeerInventario("inventario", jTable_proveedores1);
        con.LeerProveedores("proveedores", jTable_proveedores);
        
        
        jTable_empleados.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent Mouse_evt)
                {
                    JTable table = (JTable) Mouse_evt.getSource();
                    Point point = Mouse_evt.getPoint();
                    int row = table.rowAtPoint(point);
                    if(Mouse_evt.getClickCount() == 1)
               
                {
                    jtxtempLoggin.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 1).toString());
                    jtxtempCedula.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 2).toString());
                    jtxtempApellido1.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 3).toString());
                    jtxtempApellido2.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 4).toString());
                    jtxtempNombre1.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 5).toString());
                    jtxtempNombre2.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 6).toString());
                    jtxtempDireccion.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 7).toString());
                    jtxtempTelefono.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 8).toString());
                    jtxtempCorreo.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 9).toString());
                    jtxtempSeguro.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 10).toString());
                    jtxtempCargo.setText(jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 11).toString());
                }
                }
        });
        
        
        jTable_Clientes.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent Mouse_evt)
                {
                    JTable table = (JTable) Mouse_evt.getSource();
                    Point point = Mouse_evt.getPoint();
                    int row = table.rowAtPoint(point);
                    if(Mouse_evt.getClickCount() == 1)
               
                {
                    jtxtcliCedula.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 1).toString());
                    jtxtcliApellido1.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 2).toString());
                    jtxtcliApellido2.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 3).toString());
                    jtxtcliNombre1.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 4).toString());
                    jtxtcliNombre2.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 5).toString());
                    jtxtcliDireccion.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 6).toString());
                    jtxtcliTelefono.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 7).toString());
                    jtxtcliCorreo.setText(jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 8).toString());
                }
                }
        });
    }

    private PanelAdmin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbdFormulas = new javax.swing.JTabbedPane();
        jPnlFormulaGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFrtLiteralB = new javax.swing.JFormattedTextField();
        jFrtLiteralC = new javax.swing.JFormattedTextField();
        jFrtLiteralA = new javax.swing.JFormattedTextField();
        jLblLiteralA = new javax.swing.JLabel();
        jLblLiteralB = new javax.swing.JLabel();
        jLblLiteralC = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        jLblX1 = new javax.swing.JLabel();
        jLblX2 = new javax.swing.JLabel();
        jPnlMiFormula = new javax.swing.JPanel();
        Jbtn_guardar2 = new java.awt.Button();
        jTxtTitulo2 = new java.awt.TextField();
        jTxtNombre2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_empleados = new javax.swing.JTable();
        jPanel_prop = new javax.swing.JPanel();
        jLbl_titulo = new java.awt.Label();
        jLbl_editorial = new java.awt.Label();
        jLbl_anio = new java.awt.Label();
        JlblDatos = new java.awt.Label();
        jtxtempLoggin = new javax.swing.JTextField();
        jtxtempCedula = new javax.swing.JTextField();
        jtxtempApellido1 = new javax.swing.JTextField();
        jLbl_titulo1 = new java.awt.Label();
        jLbl_editorial1 = new java.awt.Label();
        jLbl_anio1 = new java.awt.Label();
        jLbl_anio2 = new java.awt.Label();
        jLbl_anio3 = new java.awt.Label();
        jtxtempNombre1 = new javax.swing.JTextField();
        Seguro = new java.awt.Label();
        jtxtempNombre2 = new javax.swing.JTextField();
        jtxtempTelefono = new javax.swing.JTextField();
        jLbl_anio5 = new java.awt.Label();
        jtxtempDireccion = new javax.swing.JTextField();
        jtxtempCorreo = new javax.swing.JTextField();
        jtxtempSeguro = new javax.swing.JTextField();
        jLbl_titulo2 = new java.awt.Label();
        jtxtempCargo = new javax.swing.JTextField();
        jtxtempApellido2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Clientes = new javax.swing.JTable();
        jPanelDatosUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblTelefono = new javax.swing.JLabel();
        jLblDireccion = new javax.swing.JLabel();
        jLblCiudad = new javax.swing.JLabel();
        jLblCorreo = new javax.swing.JLabel();
        jtxtcliApellido1 = new javax.swing.JTextField();
        jtxtcliCedula = new javax.swing.JTextField();
        jtxtcliNombre1 = new javax.swing.JTextField();
        jtxtcliApellido2 = new javax.swing.JTextField();
        jtxtcliNombre2 = new javax.swing.JTextField();
        jLblCorreo1 = new javax.swing.JLabel();
        jLblCorreo2 = new javax.swing.JLabel();
        jLblCorreo3 = new javax.swing.JLabel();
        jtxtcliDireccion = new javax.swing.JTextField();
        jtxtcliTelefono = new javax.swing.JTextField();
        jtxtcliCorreo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanelDatosUsuario1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLblNombre1 = new javax.swing.JLabel();
        jLblTelefono1 = new javax.swing.JLabel();
        jLblDireccion1 = new javax.swing.JLabel();
        jLblCiudad1 = new javax.swing.JLabel();
        jLblCorreo4 = new javax.swing.JLabel();
        jtxtcliApellido3 = new javax.swing.JTextField();
        jtxtcliCedula1 = new javax.swing.JTextField();
        jtxtcliNombre3 = new javax.swing.JTextField();
        jtxtcliApellido4 = new javax.swing.JTextField();
        jtxtcliNombre4 = new javax.swing.JTextField();
        jLblCorreo5 = new javax.swing.JLabel();
        jLblCorreo6 = new javax.swing.JLabel();
        jLblCorreo7 = new javax.swing.JLabel();
        jtxtcliDireccion1 = new javax.swing.JTextField();
        jtxtcliTelefono1 = new javax.swing.JTextField();
        jtxtcliCorreo1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_proveedores1 = new javax.swing.JTable();
        jPanelDatosUsuario2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLblNombre2 = new javax.swing.JLabel();
        jLblTelefono2 = new javax.swing.JLabel();
        jLblDireccion2 = new javax.swing.JLabel();
        jLblCiudad2 = new javax.swing.JLabel();
        jLblCorreo8 = new javax.swing.JLabel();
        jtxtcliApellido5 = new javax.swing.JTextField();
        jtxtcliCedula2 = new javax.swing.JTextField();
        jtxtcliNombre5 = new javax.swing.JTextField();
        jtxtcliApellido6 = new javax.swing.JTextField();
        jtxtcliNombre6 = new javax.swing.JTextField();
        jLblCorreo9 = new javax.swing.JLabel();
        jLblCorreo10 = new javax.swing.JLabel();
        jLblCorreo11 = new javax.swing.JLabel();
        jtxtcliDireccion2 = new javax.swing.JTextField();
        jtxtcliTelefono2 = new javax.swing.JTextField();
        jtxtcliCorreo2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_proveedores = new javax.swing.JTable();
        jPanelDatosUsuario3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLblNombre3 = new javax.swing.JLabel();
        jLblTelefono3 = new javax.swing.JLabel();
        jLblDireccion3 = new javax.swing.JLabel();
        jLblCiudad3 = new javax.swing.JLabel();
        jLblCorreo12 = new javax.swing.JLabel();
        jtxtcliApellido7 = new javax.swing.JTextField();
        jtxtcliCedula3 = new javax.swing.JTextField();
        jtxtcliNombre7 = new javax.swing.JTextField();
        jtxtcliApellido8 = new javax.swing.JTextField();
        jtxtcliNombre8 = new javax.swing.JTextField();
        jLblCorreo13 = new javax.swing.JLabel();
        jLblCorreo14 = new javax.swing.JLabel();
        jLblCorreo15 = new javax.swing.JLabel();
        jtxtcliDireccion3 = new javax.swing.JTextField();
        jtxtcliTelefono3 = new javax.swing.JTextField();
        jtxtcliCorreo3 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        jPanel_buttons = new javax.swing.JPanel();
        Jbtn_actualizar = new javax.swing.JButton();
        Jbtn_guardar = new javax.swing.JButton();
        Jbtn_eliminar = new javax.swing.JButton();
        Jbtn_nuevo = new javax.swing.JButton();

        jPnlFormulaGeneral.setBackground(new java.awt.Color(255, 204, 0));
        jPnlFormulaGeneral.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ingresa la literales y resuelve la fórmula");

        jFrtLiteralB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFrtLiteralB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrtLiteralBActionPerformed(evt);
            }
        });

        jFrtLiteralC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFrtLiteralC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrtLiteralCActionPerformed(evt);
            }
        });

        jFrtLiteralA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFrtLiteralA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrtLiteralAActionPerformed(evt);
            }
        });

        jLblLiteralA.setText("a:");

        jLblLiteralB.setText("b:");

        jLblLiteralC.setText("c:");

        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLblX1.setText("X1:");

        jLblX2.setText("x2:");

        javax.swing.GroupLayout jPnlFormulaGeneralLayout = new javax.swing.GroupLayout(jPnlFormulaGeneral);
        jPnlFormulaGeneral.setLayout(jPnlFormulaGeneralLayout);
        jPnlFormulaGeneralLayout.setHorizontalGroup(
            jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblLiteralA)
                            .addComponent(jLblLiteralB)
                            .addComponent(jLblLiteralC))
                        .addGap(27, 27, 27)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFrtLiteralA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrtLiteralC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrtLiteralB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblX1)
                            .addComponent(jLblX2))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPnlFormulaGeneralLayout.setVerticalGroup(
            jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrtLiteralA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblLiteralA))
                                .addGap(18, 18, 18)
                                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrtLiteralB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblLiteralB))
                                .addGap(18, 18, 18)
                                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrtLiteralC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblLiteralC)))
                            .addComponent(Separator))
                        .addGap(19, 19, 19))
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLblX1)
                        .addGap(52, 52, 52)
                        .addComponent(jLblX2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTbdFormulas.addTab("Fórmula General", jPnlFormulaGeneral);

        javax.swing.GroupLayout jPnlMiFormulaLayout = new javax.swing.GroupLayout(jPnlMiFormula);
        jPnlMiFormula.setLayout(jPnlMiFormulaLayout);
        jPnlMiFormulaLayout.setHorizontalGroup(
            jPnlMiFormulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPnlMiFormulaLayout.setVerticalGroup(
            jPnlMiFormulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        jTbdFormulas.addTab("Mi Fórmula", jPnlMiFormula);

        Jbtn_guardar2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        Jbtn_guardar2.setLabel("Guardar");

        jTxtTitulo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTxtNombre2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTable_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_empleados);

        jPanel_prop.setBackground(new java.awt.Color(255, 255, 102));

        jLbl_titulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_titulo.setText("Cedula");

        jLbl_editorial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_editorial.setText("Nombre1");

        jLbl_anio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_anio.setText("Nombre2");

        JlblDatos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JlblDatos.setText("Datos de empleado");

        jtxtempLoggin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempLogginActionPerformed(evt);
            }
        });

        jtxtempCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtxtempApellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempApellido1ActionPerformed(evt);
            }
        });

        jLbl_titulo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_titulo1.setText("Apellido 1");

        jLbl_editorial1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_editorial1.setText("Apellido2");

        jLbl_anio1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_anio1.setText("Telefono");

        jLbl_anio2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_anio2.setText("Seguro");

        jLbl_anio3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_anio3.setText("Cargo");

        jtxtempNombre1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempNombre1ActionPerformed(evt);
            }
        });

        Seguro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Seguro.setText("Direccion");

        jtxtempNombre2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempNombre2ActionPerformed(evt);
            }
        });

        jtxtempTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempTelefonoActionPerformed(evt);
            }
        });

        jLbl_anio5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_anio5.setText("Correo");

        jtxtempDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempDireccionActionPerformed(evt);
            }
        });

        jtxtempCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempCorreoActionPerformed(evt);
            }
        });

        jLbl_titulo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_titulo2.setText("idLoggin");

        jtxtempApellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtempApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtempApellido2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_propLayout = new javax.swing.GroupLayout(jPanel_prop);
        jPanel_prop.setLayout(jPanel_propLayout);
        jPanel_propLayout.setHorizontalGroup(
            jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_propLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addComponent(JlblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_anio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_anio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtempCorreo)
                            .addComponent(jtxtempTelefono)))
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_editorial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Seguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLbl_editorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbl_anio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLbl_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtempLoggin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtempNombre2)
                            .addComponent(jtxtempCedula)
                            .addComponent(jtxtempApellido1)
                            .addComponent(jtxtempNombre1)
                            .addComponent(jtxtempDireccion)
                            .addComponent(jtxtempApellido2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_anio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_anio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtempSeguro)
                            .addComponent(jtxtempCargo))))
                .addContainerGap())
        );
        jPanel_propLayout.setVerticalGroup(
            jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_propLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtempLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addComponent(jtxtempCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                .addComponent(jtxtempApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_propLayout.createSequentialGroup()
                                        .addComponent(jtxtempApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                                .addGap(0, 6, Short.MAX_VALUE)
                                                .addComponent(jtxtempNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLbl_editorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                                .addComponent(jtxtempNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtxtempDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Seguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLbl_anio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel_propLayout.createSequentialGroup()
                                                        .addComponent(jtxtempTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                                                .addComponent(jLbl_anio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(13, 13, 13)
                                                                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jtxtempSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLbl_anio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addComponent(jtxtempCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jLbl_anio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jtxtempCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                            .addComponent(jLbl_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel_propLayout.createSequentialGroup()
                                        .addComponent(jLbl_editorial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel_propLayout.createSequentialGroup()
                                .addComponent(jLbl_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addComponent(jLbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        JlblDatos.getAccessibleContext().setAccessibleDescription("");
        JlblDatos.getAccessibleContext().setAccessibleParent(jPanel_prop);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        jTabbedPane.addTab("Empleados", jPanel2);

        jTable_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_Clientes);

        jPanelDatosUsuario.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Datos de Cliente");

        jLblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblNombre.setText("Cedula");

        jLblTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblTelefono.setText("Apellido2");

        jLblDireccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblDireccion.setText("Apellido1");

        jLblCiudad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCiudad.setText("Nombre1");

        jLblCorreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo.setText("Nombre2");

        jtxtcliApellido1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCedula.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliApellido2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLblCorreo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo1.setText("Direccion");

        jLblCorreo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo2.setText("Telefono");

        jLblCorreo3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo3.setText("Correo");

        jtxtcliDireccion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliTelefono.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCorreo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanelDatosUsuarioLayout = new javax.swing.GroupLayout(jPanelDatosUsuario);
        jPanelDatosUsuario.setLayout(jPanelDatosUsuarioLayout);
        jPanelDatosUsuarioLayout.setHorizontalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDireccion)
                            .addComponent(jLblNombre))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliApellido1)
                            .addComponent(jtxtcliCedula)))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 280, Short.MAX_VALUE))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTelefono)
                            .addComponent(jLblCiudad)
                            .addComponent(jLblCorreo)
                            .addComponent(jLblCorreo1)
                            .addComponent(jLblCorreo2)
                            .addComponent(jLblCorreo3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliCorreo)
                            .addComponent(jtxtcliTelefono)
                            .addComponent(jtxtcliDireccion)
                            .addComponent(jtxtcliNombre1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtcliApellido2)
                            .addComponent(jtxtcliNombre2))))
                .addContainerGap())
        );
        jPanelDatosUsuarioLayout.setVerticalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jtxtcliCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion)
                    .addComponent(jtxtcliApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefono)
                    .addComponent(jtxtcliApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCiudad)
                    .addComponent(jtxtcliNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo)
                    .addComponent(jtxtcliNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo1)
                    .addComponent(jtxtcliDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo2)
                    .addComponent(jtxtcliTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo3)
                    .addComponent(jtxtcliCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Clientes", jPanel3);

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable_productos);

        jPanelDatosUsuario1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Datos de Cliente");

        jLblNombre1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblNombre1.setText("Cedula");

        jLblTelefono1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblTelefono1.setText("Apellido2");

        jLblDireccion1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblDireccion1.setText("Apellido1");

        jLblCiudad1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCiudad1.setText("Nombre1");

        jLblCorreo4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo4.setText("Nombre2");

        jtxtcliApellido3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCedula1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliApellido4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLblCorreo5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo5.setText("Direccion");

        jLblCorreo6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo6.setText("Telefono");

        jLblCorreo7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo7.setText("Correo");

        jtxtcliDireccion1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliTelefono1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCorreo1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanelDatosUsuario1Layout = new javax.swing.GroupLayout(jPanelDatosUsuario1);
        jPanelDatosUsuario1.setLayout(jPanelDatosUsuario1Layout);
        jPanelDatosUsuario1Layout.setHorizontalGroup(
            jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuario1Layout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDireccion1)
                            .addComponent(jLblNombre1))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliApellido3)
                            .addComponent(jtxtcliCedula1)))
                    .addGroup(jPanelDatosUsuario1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(jPanelDatosUsuario1Layout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTelefono1)
                            .addComponent(jLblCiudad1)
                            .addComponent(jLblCorreo4)
                            .addComponent(jLblCorreo5)
                            .addComponent(jLblCorreo6)
                            .addComponent(jLblCorreo7))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliCorreo1)
                            .addComponent(jtxtcliTelefono1)
                            .addComponent(jtxtcliDireccion1)
                            .addComponent(jtxtcliNombre3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtcliApellido4)
                            .addComponent(jtxtcliNombre4))))
                .addContainerGap())
        );
        jPanelDatosUsuario1Layout.setVerticalGroup(
            jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre1)
                    .addComponent(jtxtcliCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion1)
                    .addComponent(jtxtcliApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefono1)
                    .addComponent(jtxtcliApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCiudad1)
                    .addComponent(jtxtcliNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo4)
                    .addComponent(jtxtcliNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo5)
                    .addComponent(jtxtcliDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo6)
                    .addComponent(jtxtcliTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo7)
                    .addComponent(jtxtcliCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Productos", jPanel4);

        jTable_proveedores1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable_proveedores1);

        jPanelDatosUsuario2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Datos de Cliente");

        jLblNombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblNombre2.setText("Cedula");

        jLblTelefono2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblTelefono2.setText("Apellido2");

        jLblDireccion2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblDireccion2.setText("Apellido1");

        jLblCiudad2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCiudad2.setText("Nombre1");

        jLblCorreo8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo8.setText("Nombre2");

        jtxtcliApellido5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCedula2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliApellido6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLblCorreo9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo9.setText("Direccion");

        jLblCorreo10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo10.setText("Telefono");

        jLblCorreo11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo11.setText("Correo");

        jtxtcliDireccion2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliTelefono2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCorreo2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanelDatosUsuario2Layout = new javax.swing.GroupLayout(jPanelDatosUsuario2);
        jPanelDatosUsuario2.setLayout(jPanelDatosUsuario2Layout);
        jPanelDatosUsuario2Layout.setHorizontalGroup(
            jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuario2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuario2Layout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDireccion2)
                            .addComponent(jLblNombre2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliApellido5)
                            .addComponent(jtxtcliCedula2)))
                    .addGroup(jPanelDatosUsuario2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(jPanelDatosUsuario2Layout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTelefono2)
                            .addComponent(jLblCiudad2)
                            .addComponent(jLblCorreo8)
                            .addComponent(jLblCorreo9)
                            .addComponent(jLblCorreo10)
                            .addComponent(jLblCorreo11))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliCorreo2)
                            .addComponent(jtxtcliTelefono2)
                            .addComponent(jtxtcliDireccion2)
                            .addComponent(jtxtcliNombre5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtcliApellido6)
                            .addComponent(jtxtcliNombre6))))
                .addContainerGap())
        );
        jPanelDatosUsuario2Layout.setVerticalGroup(
            jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre2)
                    .addComponent(jtxtcliCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion2)
                    .addComponent(jtxtcliApellido5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefono2)
                    .addComponent(jtxtcliApellido6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCiudad2)
                    .addComponent(jtxtcliNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo8)
                    .addComponent(jtxtcliNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo9)
                    .addComponent(jtxtcliDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo10)
                    .addComponent(jtxtcliTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo11)
                    .addComponent(jtxtcliCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Inventario", jPanel6);

        jTable_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable_proveedores);

        jPanelDatosUsuario3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Datos de Proveedor");

        jLblNombre3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblNombre3.setText("Cedula");

        jLblTelefono3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblTelefono3.setText("Apellido2");

        jLblDireccion3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblDireccion3.setText("Apellido1");

        jLblCiudad3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCiudad3.setText("Nombre1");

        jLblCorreo12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo12.setText("Nombre2");

        jtxtcliApellido7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCedula3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliApellido8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliNombre8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLblCorreo13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo13.setText("Direccion");

        jLblCorreo14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo14.setText("Telefono");

        jLblCorreo15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo15.setText("Correo");

        jtxtcliDireccion3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliTelefono3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jtxtcliCorreo3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanelDatosUsuario3Layout = new javax.swing.GroupLayout(jPanelDatosUsuario3);
        jPanelDatosUsuario3.setLayout(jPanelDatosUsuario3Layout);
        jPanelDatosUsuario3Layout.setHorizontalGroup(
            jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuario3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuario3Layout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDireccion3)
                            .addComponent(jLblNombre3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliApellido7)
                            .addComponent(jtxtcliCedula3)))
                    .addGroup(jPanelDatosUsuario3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(jPanelDatosUsuario3Layout.createSequentialGroup()
                        .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTelefono3)
                            .addComponent(jLblCiudad3)
                            .addComponent(jLblCorreo12)
                            .addComponent(jLblCorreo13)
                            .addComponent(jLblCorreo14)
                            .addComponent(jLblCorreo15))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcliCorreo3)
                            .addComponent(jtxtcliTelefono3)
                            .addComponent(jtxtcliDireccion3)
                            .addComponent(jtxtcliNombre7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtcliApellido8)
                            .addComponent(jtxtcliNombre8))))
                .addContainerGap())
        );
        jPanelDatosUsuario3Layout.setVerticalGroup(
            jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuario3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre3)
                    .addComponent(jtxtcliCedula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDireccion3)
                    .addComponent(jtxtcliApellido7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefono3)
                    .addComponent(jtxtcliApellido8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCiudad3)
                    .addComponent(jtxtcliNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo12)
                    .addComponent(jtxtcliNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo13)
                    .addComponent(jtxtcliDireccion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo14)
                    .addComponent(jtxtcliTelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo15)
                    .addComponent(jtxtcliCorreo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosUsuario3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Proveedores", jPanel5);

        label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Panel de administración");

        jPanel_buttons.setBackground(new java.awt.Color(102, 255, 102));

        Jbtn_actualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_actualizar.setText("Actualizar");
        Jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_actualizarActionPerformed(evt);
            }
        });

        Jbtn_guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_guardar.setText("Guardar");
        Jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarActionPerformed(evt);
            }
        });

        Jbtn_eliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_eliminar.setText("Eliminar");
        Jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_eliminarActionPerformed(evt);
            }
        });

        Jbtn_nuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_nuevo.setText("Limpiar campos");
        Jbtn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buttonsLayout = new javax.swing.GroupLayout(jPanel_buttons);
        jPanel_buttons.setLayout(jPanel_buttonsLayout);
        jPanel_buttonsLayout.setHorizontalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_buttonsLayout.setVerticalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Jbtn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jbtn_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jbtn_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_buttons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFrtLiteralBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrtLiteralBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrtLiteralBActionPerformed

    private void jFrtLiteralCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrtLiteralCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrtLiteralCActionPerformed

    private void jFrtLiteralAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrtLiteralAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrtLiteralAActionPerformed

    private void Jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarActionPerformed

        int indexSelect = jTabbedPane.getSelectedIndex();
        switch(indexSelect){
            case 0:
                con.InsertarEmpleado(jtxtempLoggin, jtxtempCedula, jtxtempApellido1,
                        jtxtempApellido2, jtxtempNombre1, jtxtempNombre2, jtxtempDireccion,
                        jtxtempTelefono, jtxtempCorreo, jtxtempSeguro, jtxtempCargo); 
                
                con.LeerEmpleados("empleados", jTable_empleados);
            case 1:
                con.InsertarCliente(jtxtcliCedula, jtxtcliApellido1, jtxtcliApellido2,
                        jtxtcliNombre1, jtxtcliNombre2,jtxtcliDireccion,jtxtcliTelefono,
                        jtxtcliCorreo);
                con.LeerClientes("clientes", jTable_Clientes);
        }
    }//GEN-LAST:event_Jbtn_guardarActionPerformed

    private void Jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_actualizarActionPerformed
        // TODO add your handling code here:
        
        
        int indexSelect = jTabbedPane.getSelectedIndex();
        switch(indexSelect){
            case 0:
                String idempleado = jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 0).toString();
                con.ActualizarEmpleado(jtxtempLoggin, jtxtempCedula,jtxtempApellido1,jtxtempApellido2,
                        jtxtempNombre1,jtxtempNombre2,jtxtempDireccion,jtxtempTelefono,jtxtempCorreo,
                        jtxtempSeguro,jtxtempCargo,idempleado);
                con.LeerEmpleados("empleados", jTable_empleados);
            case 1:
                String idcliente = jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 0).toString();
                con.ActualizarCliente(jtxtcliCedula, jtxtcliApellido1, jtxtcliApellido2, jtxtcliNombre1,
                        jtxtcliNombre2,jtxtcliDireccion,jtxtcliTelefono,jtxtcliCorreo, idcliente);
                con.LeerClientes("clientes", jTable_Clientes);
        }

    }//GEN-LAST:event_Jbtn_actualizarActionPerformed

    private void Jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_eliminarActionPerformed
        // TODO add your handling code here:
        
        int indexSelect = jTabbedPane.getSelectedIndex();
        switch(indexSelect){
            case 0:
                String id = jTable_empleados.getValueAt(jTable_empleados.getSelectedRow(), 0).toString();
                con.EliminaRegistro("idempleado", "empleados", id);
                con.LeerEmpleados("empleados", jTable_empleados);
            case 1:
                String idcliente = jTable_Clientes.getValueAt(jTable_Clientes.getSelectedRow(), 0).toString();
                con.EliminaRegistro("idcliente", "clientes", idcliente);
                con.LeerClientes("clientes", jTable_Clientes);
        }
    }//GEN-LAST:event_Jbtn_eliminarActionPerformed

    private void Jbtn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_nuevoActionPerformed
        // TODO add your handling code here:
        jtxtempLoggin.setText("");
        jtxtempCedula.setText("");
        jtxtempApellido1.setText("");
        jtxtempApellido2.setText("");
        jtxtempNombre1.setText("");
        jtxtempNombre2.setText("");
        jtxtempDireccion.setText("");
        jtxtempTelefono.setText("");
        jtxtempCorreo.setText("");
        jtxtempSeguro.setText("");
        jtxtempCargo.setText("");
        
        jtxtcliCedula.setText("");
        jtxtcliApellido1.setText("");
        jtxtcliApellido2.setText("");
        jtxtcliNombre1.setText("");
        jtxtcliNombre2.setText("");
        jtxtcliDireccion.setText("");
        jtxtcliTelefono.setText("");
        jtxtcliCorreo.setText("");
    }//GEN-LAST:event_Jbtn_nuevoActionPerformed

    private void jtxtempCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempCorreoActionPerformed

    private void jtxtempDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempDireccionActionPerformed

    private void jtxtempTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempTelefonoActionPerformed

    private void jtxtempNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempNombre2ActionPerformed

    private void jtxtempNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempNombre1ActionPerformed

    private void jtxtempApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempApellido1ActionPerformed

    private void jtxtempLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempLogginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempLogginActionPerformed

    private void jtxtempApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtempApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtempApellido2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PanelAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_actualizar;
    private javax.swing.JButton Jbtn_eliminar;
    private javax.swing.JButton Jbtn_guardar;
    private java.awt.Button Jbtn_guardar2;
    private javax.swing.JButton Jbtn_nuevo;
    private java.awt.Label JlblDatos;
    private java.awt.Label Seguro;
    private javax.swing.JSeparator Separator;
    private javax.swing.JFormattedTextField jFrtLiteralA;
    private javax.swing.JFormattedTextField jFrtLiteralB;
    private javax.swing.JFormattedTextField jFrtLiteralC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblCiudad;
    private javax.swing.JLabel jLblCiudad1;
    private javax.swing.JLabel jLblCiudad2;
    private javax.swing.JLabel jLblCiudad3;
    private javax.swing.JLabel jLblCorreo;
    private javax.swing.JLabel jLblCorreo1;
    private javax.swing.JLabel jLblCorreo10;
    private javax.swing.JLabel jLblCorreo11;
    private javax.swing.JLabel jLblCorreo12;
    private javax.swing.JLabel jLblCorreo13;
    private javax.swing.JLabel jLblCorreo14;
    private javax.swing.JLabel jLblCorreo15;
    private javax.swing.JLabel jLblCorreo2;
    private javax.swing.JLabel jLblCorreo3;
    private javax.swing.JLabel jLblCorreo4;
    private javax.swing.JLabel jLblCorreo5;
    private javax.swing.JLabel jLblCorreo6;
    private javax.swing.JLabel jLblCorreo7;
    private javax.swing.JLabel jLblCorreo8;
    private javax.swing.JLabel jLblCorreo9;
    private javax.swing.JLabel jLblDireccion;
    private javax.swing.JLabel jLblDireccion1;
    private javax.swing.JLabel jLblDireccion2;
    private javax.swing.JLabel jLblDireccion3;
    private javax.swing.JLabel jLblLiteralA;
    private javax.swing.JLabel jLblLiteralB;
    private javax.swing.JLabel jLblLiteralC;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblNombre1;
    private javax.swing.JLabel jLblNombre2;
    private javax.swing.JLabel jLblNombre3;
    private javax.swing.JLabel jLblTelefono;
    private javax.swing.JLabel jLblTelefono1;
    private javax.swing.JLabel jLblTelefono2;
    private javax.swing.JLabel jLblTelefono3;
    private javax.swing.JLabel jLblX1;
    private javax.swing.JLabel jLblX2;
    private java.awt.Label jLbl_anio;
    private java.awt.Label jLbl_anio1;
    private java.awt.Label jLbl_anio2;
    private java.awt.Label jLbl_anio3;
    private java.awt.Label jLbl_anio5;
    private java.awt.Label jLbl_editorial;
    private java.awt.Label jLbl_editorial1;
    private java.awt.Label jLbl_titulo;
    private java.awt.Label jLbl_titulo1;
    private java.awt.Label jLbl_titulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelDatosUsuario;
    private javax.swing.JPanel jPanelDatosUsuario1;
    private javax.swing.JPanel jPanelDatosUsuario2;
    private javax.swing.JPanel jPanelDatosUsuario3;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_prop;
    private javax.swing.JPanel jPnlFormulaGeneral;
    private javax.swing.JPanel jPnlMiFormula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable_Clientes;
    private javax.swing.JTable jTable_empleados;
    private javax.swing.JTable jTable_productos;
    private javax.swing.JTable jTable_proveedores;
    private javax.swing.JTable jTable_proveedores1;
    private javax.swing.JTabbedPane jTbdFormulas;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTxtNombre2;
    private java.awt.TextField jTxtTitulo2;
    private javax.swing.JTextField jtxtcliApellido1;
    private javax.swing.JTextField jtxtcliApellido2;
    private javax.swing.JTextField jtxtcliApellido3;
    private javax.swing.JTextField jtxtcliApellido4;
    private javax.swing.JTextField jtxtcliApellido5;
    private javax.swing.JTextField jtxtcliApellido6;
    private javax.swing.JTextField jtxtcliApellido7;
    private javax.swing.JTextField jtxtcliApellido8;
    private javax.swing.JTextField jtxtcliCedula;
    private javax.swing.JTextField jtxtcliCedula1;
    private javax.swing.JTextField jtxtcliCedula2;
    private javax.swing.JTextField jtxtcliCedula3;
    private javax.swing.JTextField jtxtcliCorreo;
    private javax.swing.JTextField jtxtcliCorreo1;
    private javax.swing.JTextField jtxtcliCorreo2;
    private javax.swing.JTextField jtxtcliCorreo3;
    private javax.swing.JTextField jtxtcliDireccion;
    private javax.swing.JTextField jtxtcliDireccion1;
    private javax.swing.JTextField jtxtcliDireccion2;
    private javax.swing.JTextField jtxtcliDireccion3;
    private javax.swing.JTextField jtxtcliNombre1;
    private javax.swing.JTextField jtxtcliNombre2;
    private javax.swing.JTextField jtxtcliNombre3;
    private javax.swing.JTextField jtxtcliNombre4;
    private javax.swing.JTextField jtxtcliNombre5;
    private javax.swing.JTextField jtxtcliNombre6;
    private javax.swing.JTextField jtxtcliNombre7;
    private javax.swing.JTextField jtxtcliNombre8;
    private javax.swing.JTextField jtxtcliTelefono;
    private javax.swing.JTextField jtxtcliTelefono1;
    private javax.swing.JTextField jtxtcliTelefono2;
    private javax.swing.JTextField jtxtcliTelefono3;
    private javax.swing.JTextField jtxtempApellido1;
    private javax.swing.JTextField jtxtempApellido2;
    private javax.swing.JTextField jtxtempCargo;
    private javax.swing.JTextField jtxtempCedula;
    private javax.swing.JTextField jtxtempCorreo;
    private javax.swing.JTextField jtxtempDireccion;
    private javax.swing.JTextField jtxtempLoggin;
    private javax.swing.JTextField jtxtempNombre1;
    private javax.swing.JTextField jtxtempNombre2;
    private javax.swing.JTextField jtxtempSeguro;
    private javax.swing.JTextField jtxtempTelefono;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
